version: '{build}'
image: Visual Studio 2017  
pull_requests:  
  do_not_increment_build_number: false
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
after_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
          choco install nuget.commandline -y
          .\docs\buildDocu.ps1 -Deploy
        }
test:
  assemblies:
    - '**\*test*.dll'
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: q9CTIytwzn07gcypWBXc1JNw5V1+kFX54YosfZYxGAKchBoCCr4Gpduso4ntoKw2
  on:
    branch: master
    appveyor_repo_tag: true