environment:
  git_user: "OpenPublishBuild"
  git_email: "info@wacore.com"
  git_access_token:
    secure: 4vngnALEVBWUWd4tuLHADxd5vF26geMyGw0dGjun494fq/W0sLiQAJxhXXYsdD39

version: '{build}'
image: Visual Studio 2017  
pull_requests:  
  do_not_increment_build_number: false
nuget:  
  disable_publish_on_pr: true
before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            choco install nuget.commandline -y
        }
build_script:  
- ps: .\Build.ps1
after_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
          .\docs\buildDocu.ps1 -Deploy
        }
test:
  assemblies:
    - '**\*test*.dll'
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: q9CTIytwzn07gcypWBXc1JNw5V1+kFX54YosfZYxGAKchBoCCr4Gpduso4ntoKw2
  on:
    branch: master
    appveyor_repo_tag: true