environment:
  git_user: "CiBuildDocu"
  git_email: "CiBuildDocu@wacore.com"
  git_access_token:
    secure: /OB1V/jwz6+VVu62c1k3dycubqHbRbYb/P/lieXf54NjvG5jQSOTVAjIOueVbgMR
version: '{build}'
image: Visual Studio 2017  
skip_branch_with_pr: true
pull_requests:  
  do_not_increment_build_number: false
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
after_build:
  - ps: |
        If (($env:APPVEYOR_REPO_BRANCH -eq "docu"))
        {
          choco install nuget.commandline -y
          .\docs\buildDocu.ps1
          
          if ($lastexitcode -ne 0){
            throw [System.Exception] "docfx build failed with exit code $lastexitcode."
          }
          
          # Configuring git credentials
          Write-Host "`n[Configuring git credentials]" -ForegroundColor Green
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_access_token):x-oauth-basic@github.com`n"
          git config --global user.email $env:git_email
          git config --global user.name $env:git_user
          
          # Checkout gh-pages to folder origin_site
          Write-Host "`n[Checkout gh-pages]" -ForegroundColor Green
          git clone --quiet --no-checkout https://github.com/HerbertBodner/webapp-core.git -b gh-pages origin_site
          
          # Copy origin_site/.git to docs/_site
          Write-Host "`n[Copy origin_site/.git to docs/_site]" -ForegroundColor Green
          Copy-Item origin_site/.git docs/_site -recurse
          
          # Add changes
          Write-Host "`n[Add changes]" -ForegroundColor Green
          CD docs/_site
          git add -A 2>&1
          
          # Show changes
          Write-host "`n[git -C docs/_site add -A]" -ForegroundColor Green
          git -C docs/_site add -A
          
          # Committing changes
          Write-host "`n[Committing changes]" -ForegroundColor Green
          git commit -m "CI Updates" -q
          git push origin gh-pages -q
          cd ..
          cd ..
        }
test:
  assemblies:
    - '**\*test*.dll'
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: q9CTIytwzn07gcypWBXc1JNw5V1+kFX54YosfZYxGAKchBoCCr4Gpduso4ntoKw2
  on:
    branch: master
    appveyor_repo_tag: true